
name: Thusia

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_ROOT_PASSWORD: root
    networks:
      - my-docker-network

  suitecrm:
    image: ddd/dd
    container_name: crm
    environment:
        DB_HOST: mariadb
        ALLOW_EMPTY_PASSWORD: no
        SUITECRM_USERNAME: admin
        SUITECRM_PASSWORD: admin
        SUITECRM_DATABASE_USER: root
        SUITECRM_DATABASE_PASSWORD: root
        SUITECRM_DATABASE_NAME: crm_db
    networks:
      - my-docker-network
    ports:
      # We need 8080 for the REST API of SuiteCRM and 8443 for the web interface on HTTPS.
      - "8080:8080"
      - "8443:8443"
      - "8086:80"
    depends_on:
      - mariadb

networks:
  my-docker-network:

