
name: Thusia

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_ROOT_PASSWORD: root
    networks:
      - my-docker-network

  suitecrm:
    image: admwinther/suitecrm:8.6.0
    container_name: crm
    environment:
        DB_HOST_ADDRESS: mariadb
        ALLOW_EMPTY_PASSWORD: no
        ADMIN_USERNAME: admin
        ADMIN_PASSWORD: admin
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_PORT: 3306
        DB_NAME: crm_db
        SITE_URL: http://localhost:8086
    networks:
      - my-docker-network
    ports:
      # We need 8080 for the REST API of SuiteCRM and 8443 for the web interface on HTTPS.
      - "8080:8080"
      - "8443:8443"
      - "8086:80"
    depends_on:
      - mariadb

networks:
  my-docker-network:

